env: local

timeout-server: 100
gateway:
  host: "localhost"
  port: 8080

postgres:
  host: "localhost"
  port: 5432
  user: "user"
  db_name: "history"
  password: "12345678"
  sslmode: "disable"

qdrant:
  host: "localhost"
  port: 6334
  name-collection: "wiki-vectors"
  batch-size: 100
  limit-points: 10
  score-threshold: 0.3

parser:
  browser-path: "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"